"""Add barcode to articles

Revision ID: 1e337eeb078c
Revises: 7caa61e22577
Create Date: 2026-09-04 16:20:44.017704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e337eeb078c'
down_revision = '7caa61e22577'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('barcode', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_articles_barcode'), 'articles', ['barcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_barcode'), table_name='articles')
    op.drop_column('articles', 'barcode')
    # ### end Alembic commands ###
