"""add user permissions

Revision ID: 7caa61e22577
Revises: 6e83880e1671
Create Date: 2026-09-04 11:56:44.430838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caa61e22577'
down_revision = '6e83880e1671'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
